#########################################
#The main configuration.yaml - see my   #
#README.md for information on how I have#
#structured and organised this file     #
#and the !include files that it links to#
#########################################

##################
## Core program ##
##################

homeassistant: !include config/core/homeassistant.yaml

###################################
## Web interface UX and security ##
###################################

frontend:
  themes: !include_dir_merge_named config/interface/themes/
  javascript_version: latest
config:
map:
group: !include_dir_merge_named config/interface/group/
http: !include config/interface/http.yaml
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token
recorder:
  purge_interval: 7
  purge_keep_days: 14
logbook: !include config/interface/logbook.yaml

#######################################
## My components/devices/sensors/etc ##
#######################################

#zwave:
#  usb_path: /dev/ttyAMA0
light:
  platform: hue
  host: !secret hue_light_host
emulated_hue: !include config/components/emulated_hue.yaml
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 250
mqtt: !include config/components/mqtt.yaml  
zone: !include_dir_list config/components/zone/
media_player: !include config/components/media_player.yaml
tts:
  - platform: google
    cache: false
telegram_bot: !include config/components/telegram_bot.yaml
notify: !include config/components/notify.yaml
camera: !include_dir_list config/components/camera/
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
sun:
sensor: !include_dir_merge_list config/components/sensor/
hue:
weblink: !include config/components/weblink.yaml
updater:
  include_used_components: true

#######################################
## My automations/scripts/scenes/etc ##
#######################################

automation: !include_dir_list config/etc/automation/
script: !include_dir_merge_named config/etc/script/
scene: !include_dir_list config/etc/scene/
input_boolean: !include config/etc/input_boolean.yaml
input_select: !include config/etc/input_select.yaml
shell_command: !include config/etc/shell_command.yaml