#########################################
#The main configuration.yaml - see my   #
#README.md for information on how I have#
#structured and organised this file     #
#and the !include files that it links to#
#########################################

##################
## Core program ##
##################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret time_zone
  unit_system: metric
  customize: !include_dir_merge_named config/core/customize/
  customize_glob: !include config/core/customize_glob.yaml
  packages: !include_dir_named config/core/packages/  

group: !include_dir_merge_named config/group/

#######################################
## My components/devices/sensors/etc ##
#######################################



google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
sensor: !include_dir_merge_list config/components/sensor/
updater:
  include_used_components: true

#######################################
## My automations/scripts/scenes/etc ##
#######################################

automation: !include_dir_list config/etc/automation/
script: !include_dir_merge_named config/etc/script/
scene: !include_dir_list config/etc/scene/
