- platform: ping
  host: !secret hue_light_host
  name: Hue Hub

- platform: ping
  host: !secret switch_tplink_host
  name: TP Link

- platform: ping
  host: !secret switch_broadlink_host
  name: Broadlink