######################################
#Sets a boolean when the sun comes up#
######################################

alias: 'sun going up'
initial_state: 'on'
trigger:
  platform: sun
  event: sunrise
  offset: '+00:35:00'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.sunset_offset