###########################################
#Sets a boolean when the sun is going down#
###########################################

alias: 'sun going down'
initial_state: 'on'
trigger:
  platform: sun
  event: sunset
  offset: '-00:35:00'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.sunset_offset