#################################
#Notifies me via telegram when  #
#an update for HASS is available#
#################################

alias: 'Update Available Notifications'
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.ha_upstream
action:
  service: notify.telegram_marc
  data:
    message: 'Update for Home Assistant is available.  https://home-assistant.io/blog/'