####################################
#Configures what is/is not recorded#
####################################

include:
  entities:
    - sensor.date


exclude:
  domains:
    - weblink
    - sensor
  entities:
    - group.hue