################################
#A one-touch scene controller  #
################################

master_bedroom_tropical_twilight:
  sequence:
    - service: light.hue_activate_scene
      data:
        group_name: "Master Bedroom"
        scene_name: "Tropical twilight"