###########################################################
#                                                         #
# This file runs a check of my configuration before it is #
# merged in to the master branch on Github to ensure that #
# the code in the repo is fully valid                     #
#                                                         #
###########################################################


version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

jobs:

### Validate docker-compose file

  build:
    docker:
      - image: alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check docker-compose
          command: docker-compose config -q

### Validate Homeassistant configuration

  test:
    docker:
      - image: homeassistant/home-assistant:rc
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            mv .bin/github_resources/secrets_redacted.yaml homeassistant/secrets.yaml
            cd /usr/src/app
            python -m homeassistant -c ~/repo/homeassistant --script check_config --info all

