###################################
#Brings lights up when media stops#
###################################

alias: 'Media player stopped (lights)'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.living_room_kodi
    to: 'idle'
condition:    
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  service: scene.turn_on
  entity_id: scene.livingroom_bright