####################################
#Brings lights up when media pauses#
#--checks it is video (not music)###
####################################

alias: 'Media player paused (lights)'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.living_room_kodi
    to: 'paused'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states.media_player.living_room_kodi.attributes.media_content_type == "tvshow" }}'
      - condition: template
        value_template: '{{ states.media_player.living_room_kodi.attributes.media_content_type == "movie" }}'
action:
  service: scene.turn_on
  entity_id: scene.livingroom_bright