#zwave:
#  usb_path: /dev/ttyAMA0


hue:
  bridges:
    - host: !secret hue_light_host
    
    
media_player:
  - platform: cast

  - platform: kodi
    name: Living Room Kodi
    host: !secret media_host
    port: !secret media_port
    enable_websocket: false
    username: !secret media_username
    password: !secret media_password
    turn_off_action:
      service: media_player.kodi_call_method
      data_template:
        entity_id: '{{ entity_id }}'
        method: System.Shutdown
        
    
switch: 
  - platform: tplink
    host: !secret switch_tplink_host

  - platform: broadlink
    host: !secret switch_broadlink_host
    mac: !secret switch_broadlink_mac
    friendly_name: 'IR remote'
    switches:
      tv_lg_on_off:
        friendly_name: 'TV power'
        command_on: 'JgAAAQABJ5QVEBISFTQUERUQExITERUQFTQVNBUREjcSNxM2FDUTNhMRFREUNRITEhIUERQ1FTQVNBU0FBETNxI3FDUTERUQFQAFJAABKUgTAAxOAAEoRxMADE4AASdJFQAMTAABJ0gVAAxNAAEoSBMADE4AAShHFQAMTAABJ0kTAAxOAAEoRxUADE0AAShHFAAMTQABKUcVAAxMAAEoRxUADE0AAShHFQAMTQABKEcUAAxNAAEoSBQADE0AAShHFQAMTQABKEgSAAxOAAEpRxQADE0AAShIFAAMTAABKUcVAAxNAAEoRxQADE0AAShIFAAMTQABKEcUAAxNAAEnSRQADQUAAAAAAAAAAA=='
        command_off: 'JgCAAAABKZITERUQFTQVEBMSExEVEBUQEzYUNhMRFDUVNBU0FTQVNRQ1FBEUNRUQExEVEBU0FTQVEBM2FBEUNRQ1FTQVEBUQEwAFJwABJ0gVAAxNAAEnSBQADE0AAShIEwAMTgABKEcVAAxMAAEpRxUADE0AAShHEwAMTgABKEgUAA0FAAAAAAAAAAA='
      tv_lg_hdmi_1:
        friendly_name: 'TV Hdmi 1'
        command_on: 'ZNyOPZtPBS3RwnscCDbyCxUQExITERUQFTQVNA=='
#      tv_lg_hdmi_2:
#        friendly_name: 'TV Hdmi 2'
#        command_on: ''


input_select:
  living_room_scenes:
    name: Scenes
    options:
      - Select
      - Dim
      - Bright
    initial: Select
    icon: mdi:creation

  master_bedroom_scenes:
    name: Scenes
    options:
      - Select
      - Arctic Aurora
      - Bright
      - Concentrate
      - Dimmed
      - Energize
      - Nightlight
      - Read
      - Relax
      - Savanna Sunset
      - Spring Blossom
      - Tropical Twilight
    initial: Select
    icon: mdi:creation


binary_sensor:
  - platform: ping
    host: !secret hue_light_host
    name: Hue Hub

  - platform: ping
    host: !secret switch_tplink_host
    name: TP Link

  - platform: ping
    host: !secret switch_broadlink_host
    name: Broadlink

  - platform: ping
    host: !secret cctv_host
    name: CCTV
