######################################
#This automation switches on all the #
#lights when instructed via telegram #
######################################

alias: 'Telegram set all lights on'
initial_state: 'on'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/onALL'
action:
  - service: homeassistant.turn_on
    entity_id: light.all_hue_lights
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: 'All lights have been turned on'