#################################
#Placing cards/entites on a tab #
#################################

master_bedroom:
  view: yes
  name: Master Bedroom
  icon: mdi:hotel
  entities:
    - group.master_bedroom_lights
    - group.masterbed_alarm_clock