###########################################
#Switches the living room/landing lights  #
#on when it is sunset and somebody is home#
###########################################

alias: 'Lights on when dark - arriving home'
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.home_status
  to: 'Occupied'
condition:
  condition: state
  entity_id: sensor.dark_outside
  to: 'true'
action:
  - service: scene.turn_on
    entity_id: scene.livingroom_bright
  - service: script.landing_light_scene