#################################
#Placing cards/entites on a tab #
#################################

boys_room:
  view: yes
  name: Boys Room
  icon: mdi:human-handsdown
  entities:
    - group.boys_alarm_clock