#################################
#Placing cards/entites on a tab #
#################################

information:
  view: yes
  name: Information
  icon: mdi:information-variant
  entities:
    - group.phone_trackers
    - group.environment
    - group.calendar
    - group.calendar_2
    - group.system
    - group.hue
    - group.devices
    - group.time
    - group.zwave
    - group.weblink
    - group.travis_ci