################################
#Hidden entities, setting icons#
#and adding friendly names     #
################################

#Lights
light.master_bedroom:
  hidden: true

light.living_room:
  hidden: true

light.landing_g:
  hidden: true

light.bathroom_g:
  hidden: true

#Input_boolean
input_boolean.sunset_offset:
  hidden: true

#Groups
group.all_automations:
  hidden: false

group.all_scripts:
  hidden: false
  control: hidden