################################
#Hidden entities, setting icons#
#and adding friendly names     #
################################

sensor.ssl_cert_expiry:
  friendly_name: "SSL certificate expiry"
  icon: mdi:security-home

sensor.ha_upstream:
  friendly_name: "Upstream HA version"
  icon: mdi:cloud-sync

sensor.installed_ha_version:
  icon: mdi:home-outline

sensor.calendar:
  icon: mdi:calendar-text

sensor.dark_outside:
  icon: mdi:theme-light-dark

sensor.bad_weather:
  icon: mdi:weather-snowy-rainy

sensor.home_status:
  icon: mdi:home-map-marker

sensor.master_bedroom_switch:
  icon: mdi:remote

sensor.mfsocialhomeassistant_last_build_id:
  friendly_name: "Last build ID"

sensor.mfsocialhomeassistant_last_build_finished_at:
  friendly_name: "Last build time"

sensor.mfsocialhomeassistant_last_build_state:
  friendly_name: "Status"

sensor.mfsocialhomeassistant_state:
  hidden: true

sensor.mfsocialhomeassistant_last_build_started_at:
  hidden: true

sensor.mfsocialhomeassistant_last_build_duration:
  hidden: true