########################################
# A script that plays the Sleep radio  #
# station for an hour over the         #
# chromecast in the bedroom, gradually #
# decreasing the volume level and then #
# switches off the chromecast and light#
########################################

lullaby:
  alias: Lullaby Mode
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomcca
        volume_level: '0.20'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: http://37.59.28.208:8722/stream
        media_content_type: 'audio/mp4'
    - service: light.hue_activate_scene
      data:
        group_name: "Master Bedroom"
        scene_name: "Nightlight"
    - delay: '00:15:00'
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomcca
        volume_level: '0.15'
    - delay: '00:15:00'
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomcca
        volume_level: '0.10'
    - delay: '00:15:00'
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomcca
        volume_level: '0.05'
    - delay: '00:15:00'
    - service: media_player.turn_off
      data:
        entity_id: media_player.bedroomcca
    - service: homeassistant.turn_off
      data:
        entity_id: light.master_bedroom