###########################
#Shell scripts that can be#
#run on the system from HA#
###########################

renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

upgrade_hass: /bin/bash /home/hass/.homeassistant/extras/bash_scripts/upgrade-hass.sh

sync_dropbox: /bin/bash python /home/hass/extras/bash_scripts/Dropbox-Uploader/dropbox_sync.py