###########################
#Shell scripts that can be#
#run on the system from HA#
###########################

upgrade_hass: /home/hass/.homeassistant/extras/bash_scripts/upgrade-hass.sh

sync_dropbox: 'python /home/hass/extras/bash_scripts/dropbox_sync.py'