#################################
#Placing entities on the card   #
#################################

Time:
  - sensor.time
  - sensor.date

Environment:
  - sun.sun
  - sensor.moon
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_cloud_coverage
  - sensor.dark_sky_daily_high_apparent_temperature
  - sensor.dark_sky_daily_high_temperature
  - sensor.dark_sky_daily_low_apparent_temperature
  - sensor.dark_sky_daily_low_temperature
  - sensor.dark_sky_daily_max_precip_intensity
  - sensor.dark_sky_daily_summary
  - sensor.dark_sky_dew_point
  - sensor.dark_sky_hourly_summary
  - sensor.dark_sky_humidity
  - sensor.dark_sky_minutely_summary
  - sensor.dark_sky_ozone
  - sensor.dark_sky_precip
  - sensor.dark_sky_precip_intensity
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_pressure
  - sensor.dark_sky_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_visibility
  - sensor.dark_sky_wind_bearing
  - sensor.dark_sky_wind_speed

Email Security: !secret email_security

Calendar:
  - sensor.calendar

Security Sensors:
  - binary_sensor.living_room_android_motion_active