##################################
#Notifies me if the havibeenpwned#
#sensor activates for any of my  #
#email addresses if breached     #
##################################

alias: 'Breach email haveibeenpwned connor'
trigger:
  platform: numeric_state
  entity_id: !secret sensor_email_connor
  above: 0
action:
  service: notify.telegram_marc
  data:
    message: 'Warning - HaveIbeenPwned detected a breach on Connor email address'