################################
#A one-touch scene controller  #
################################

name: Master bedroom wake up
entities:
  light.master_bedroom:
    state: on
    transition: 120
    brightness: 180