#############################################
#Switches on the master bedroom lights when #
#we are going up to bed via a press and hold#
#on the off switch for the living room light#
#############################################

alias: bedtime lights
trigger:
  platform: state
  entity_id: sensor.living_room_switch
  to: '4_hold'
action:
  service: script.master_bedroom_relax